name: myapp
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Mantido o formato de range, ajustado para Dart 3.x

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # Ajustado para uma versão estável e compatível

# A seção 'flutter' é onde as imagens são declaradas
flutter:

  uses-material-design: true

  # 1. CORREÇÃO: Bloco 'assets' para que o Flutter reconheça suas imagens.
  assets:
    # IMPORTANTE: A linha abaixo habilita TUDO que está dentro da pasta 'assets/img/'
    - assets/img/icons.png
    - assets/img/camera.png
    - assets/img/alface.jpg
    - assets/img/logo.png
    - assets/img/logo2.png
    - assets/img/bg-folhas.png
    - assets/img/folhaDoente1.png
    - assets/img/tomates.png
    - assets/img/tomateDoente.png
    - assets/img/green.png
    - assets/img/yellow.png
    - assets/img/red.png
    - assets/img/settings.png
    - assets/img/home.png
    - assets/img/user.png